# components:
# PLAYER
# - has 3 lives


# GAME
# - if player gets wrong question, they lose a life
# - game over when one player loses all lives
# - when game over, announce who won + the score 

# MATH QUESTION
# - every turn, a new math question generated by picking two randomnumbers (1-20)


# TURN MANAGER
# - player who's turn it is has to answer that question
# - end of every turn, output new player scores

# MAIN
# - runs the file, ends the file

# require './game.rb'

# game = Game.new()

# puts "Welcome to Millie's Math House - Lighthouse Edition"






